# Generated by Django 5.2.7 on 2026-03-09 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('best_time_to_visit', models.CharField(blank=True, default='', max_length=255)),
                ('image', models.URLField(blank=True, default='', max_length=500)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('travel_tips', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='api.city')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('historical', 'Historical'), ('nature', 'Nature'), ('adventure', 'Adventure'), ('religious', 'Religious'), ('beach', 'Beach'), ('cultural', 'Cultural')], default='historical', max_length=50)),
                ('timing', models.CharField(blank=True, default='', max_length=100)),
                ('entry_fee', models.CharField(blank=True, default='Free', max_length=100)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('image', models.URLField(blank=True, default='', max_length=500)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='api.city')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
